### ISSUE TITLE
Default config should be more persistent

### ISSUE THREAD

**Issue by colton-citus** [citusdata/docker#102]
Current Docker config does not have persistent storage configured, and may lose data unexpectedly. This issue is being opened to suggest adding default volumes with a docker-config like this:

```
services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:7.5.1'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master']
    volumes:
      - pgdata_master:/var/lib/postgresql/data
  worker:
    image: 'citusdata/citus:7.5.1'
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    volumes:
      - pgdata_worker:/var/lib/postgresql/data
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'membership_manager_test'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
volumes:
  pgdata_master:
  pgdata_worker:
```
