### ISSUE TITLE
Worker node not being added

### ISSUE THREAD

**Issue by mhaagens** [citusdata/docker#124]
docker-compose.yml
```
version: "2.1"
services:
  master:
    build: ./docker/postgres
    image: 'citus:local'
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    labels: ['com.citusdata.role=Master']
    restart: unless-stopped
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    volumes:
      - ./docker/postgres/data/master:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  worker:
    build: ./docker/postgres
    image: 'citus:local'
    labels: ['com.citusdata.role=Worker']
    restart: unless-stopped
    depends_on: { manager: { condition: service_healthy } }
    volumes:
      - ./docker/postgres/data/worker:/var/lib/postgresql/data
    env_file:
      - ./.env
  manager:
    image: 'citusdata/membership-manager:0.2.0'
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
    restart: unless-stopped
    env_file:
      - ./.env
```

Everything seems to work, except no active nodes are returned when running `SELECT master_get_active_worker_nodes();`
