### ISSUE TITLE
Hostname error for image

### ISSUE THREAD

**Issue by xyrintech** [citusdata/docker#129]
`SQLSTATE[08006] [7] could not translate host name "citus_master" to address: Name or service not known`

```
c8adcc9da16c        citusdata/membership-manager:0.2.0   "python -u ./manager…"   23 minutes ago      Up 7 minutes (healthy)                                              citus_manager
b774fdb21b50        citusdata/citus:8.2.2                "docker-entrypoint.s…"   23 minutes ago      Up 7 minutes (healthy)   0.0.0.0:5433->5432/tcp                     citus_master
```

```
version: '2.1'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:8.2.2'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master']
    environment:
    - POSTGRES_DB=default
    - POSTGRES_USER=default
    - POSTGRES_PASSWORD=secret
  worker:
    image: 'citusdata/citus:8.2.2'
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    environment:
    - POSTGRES_DB=default
    - POSTGRES_USER=default
    - POSTGRES_PASSWORD=secret
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
    environment:
    - POSTGRES_DB=default
    - POSTGRES_USER=default
    - POSTGRES_PASSWORD=secret

```

Seems to have some issue with image when trying to connect with image with any web application
