### ISSUE TITLE
Error connecting citus-manger to master.

### ISSUE THREAD

**Issue by mahajanankur** [citusdata/docker#184]
I am using the Citus version 9.2.4 with docker. I am trying to start the containers by docker-compose but I am unable to connect to the master by citus-manager.

I used V9.2.2 before upgrading to 9.2.4 with the same compose and success.

My docker-compose.yml looks like.

```
version: '2.2'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'citus:9.2.4'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    environment: &AUTH
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    labels: ['com.citusdata.role=Master']
    # volumes:
    #   - pgdata_master:/var/lib/postgresql/data

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'citus:9.2.4'
    environment: *AUTH
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    # volumes:
    #   - pgdata_worker:/var/lib/postgresql/data

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    build:
      context: ../membership-manager
      dockerfile: Dockerfile
    image: 'citus-manager:0.2.1'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    environment: *AUTH
    depends_on: { master: { condition: service_healthy } }

# volumes:
#   pgdata_master:
#   pgdata_worker:
```

![citus-manager](https://user-images.githubusercontent.com/7963490/78859831-3137ce00-7a4e-11ea-9a85-297d48b196ec.png)
