### ISSUE TITLE
Cannot run docker

### ISSUE THREAD

**Issue by neerajdangol** [citusdata/docker#35]
When I run 
`docker-compose -p citus up -d`
it gives the following error:

`Pulling manager (citusdata/membership-manager:latest)...
ERROR: repository citusdata/membership-manager not found: does not exist or no pull access`

docker-compose.yml configuration:

```
version: '3'

services:
  master:
    container_name: 'citus_master'
    image: 'citusdata/citus:7.0.0'
    ports: ['5432:5432']
    labels: ['com.citusdata.role=Master']
  worker:
    image: 'citusdata/citus:7.0.0'
    labels: ['com.citusdata.role=Worker']
    depends_on: ['manager']
  manager:
    container_name: 'citus_manager'
    image: 'citusdata/membership-manager:latest'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: ['master']
```
I'm running docker on mac
