### ISSUE TITLE
Docker Image doesn't work when specifying POSTGRES_USER/PASSWORD

### ISSUE THREAD

**Issue by saicitus** [citusdata/docker#75]
When `POSTGRES_USER and PASSWORD` is specified, the setup leads to errors whilst running queries which require distributed planning. Even a simple create_distributed_table fails.
The error message is: `Detail: fe_sendauth: no password supplied`.

This doesn’t happen when executing with the default setup.

**Comment by saicitus** [comment]
The docker-compose file which was used is on these lines:
```
version: '2.1'
services:
  master: # The communication between manager and this only works if it's named master. So.. we shouldn't change it.
      image: 'citusdata/citus:7.3.0'
      ports: ["0:5432"]
      labels: ['com.citusdata.role=Master']

  citus_worker:
      image: 'citusdata/citus:7.3.0'
      labels: ['com.citusdata.role=Worker']
      depends_on: { citus_manager: { condition: service_healthy } }

  citus_manager:
      image: 'citusdata/membership-manager:0.2.0'
      volumes: ['/var/run/docker.sock:/var/run/docker.sock']
      depends_on: { master: { condition: service_healthy } }
```
